config/routes.rb
Rails.application.routes.draw do
  

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'users/confirm' => "users#confirm"
  get "/books/:id" => "books#show"



  root 'welcome#index'

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
  }
  
  resources :boards , :only => [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :board_messages, :only => [:create, :edit, :destroy, :update]
  
  resources :admins, :only => [:index]
  
  devise_scope :user do
    post "update", :to => "users/registrations#update"
    get "delete", :to => "users/registrations#delete"
    patch "complete", :to => "users/registrations#complete"
  end
  
  resources :users, only: [:show, :index] do
    member do
     get :likes
    end
  end
  
  
  resources :books, only: [:index, :show]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :inquiries, only: [:index, :create, :new] do
    resources :answers, only: [:new, :create]
  end
  
  post 'inquiry/confirm' => 'inquiries#confirm'   

  


   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
         
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :board_messages, dependent: :destroy
  has_many :boards, dependent: :destroy
  
  has_many :favorites, dependent: :destroy
  has_many :favboards, through: :favorites, source: :board

        
  def prefecture_name
     JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end   
  
  def prefecture_name=(prefecture_name)
     self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end 

   
  
  mount_uploader :icon, ImgUploader
  
  def update_without_current_password(params, *options)
  params.delete(:current_password)
  
      if params[:password].blank? && params[:password_confirmation].blank?
        params.delete(:password)
        params.delete(:password_confirmation)
      end
  
      result = update_attributes(params, *options)
      clean_up_passwords
      result
  end
    

  #お気にり登録判定
  def already_liked?(board)
    self.favorites.exists?(board_id: board.id)
  end 
    

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update, :confirm]
  # before_action :create, only: [:create]

  # def create
    # super do 
    #   resource.update(confirmed_at: Time .now.utc) #Welcomeメールを送信した上で、skip_confirmation!と同一処理を行う
    # end 
  # end
  
  
  
  
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end
  # def edit
  #   current_user.assign_attributes(account_update_params)
  # end
  
  # def confirm
  #   @user = User.new(account_update_params)
  #   if @user.valid?
  #     render :action => 'confirm'
  #   else
  #   render :action => 'new'
  #   end
  #   # logger.debug("========================== params = #{@user.last_name}")
  #   # logger.debug("========================== params = #{@user.postcode}")
  #   # @params = params[:user]
  # end
  
  def confirm 
    @user = User.new(account_update_params)
    if @user.valid?
    flash[:notice]="会員登録が完了されました！内容を確認してください！"
    render :action => 'confirm'
    else
    render :action => 'new'
    end
  end
  
  def complete
  end
  
  def delete
  end
  
  
  protected
  

  def configure_sign_up_params
    flash[:notice]="仮登録完了です！"
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:icon, :last_name, :first_name, :last_name_kana, :first_name_kana, :gender, :postcode, :prefecture_name, :address_city, :address_street, :address_building, :college, :major, :email, :password, :password_confirmation])
  end
  
  def after_sign_up_path_for(resource)
    edit_user_registration_path
  end
  
  def after_update_path_for(resource)
    complete_path
  end
  #  
  # edit_user_registration_path
  # end
  # user_path(id: current_user.id)
  # def after_update_path_for(resource)
  #   user_registration_path(id: current_user.id)
  # end
  
  # def after_confirm_path_for(resource)
  #   user_registration_path(id: current_user.id)
  # end
  
  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
   # def configure_save_params
  #     devise_parameter_sanitizer.permit(:complete, keys[ :last_name, :first_name, :last_name_kana, :first_name_kana,:gender, :postcode, :prefecture_code, :address_city, :address_street, :address_building, :college, :major])
  # end
  # 追記する
  

    def update_resource(resource, params)
      resource.update_without_current_password(params)
    end
  


end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!, only: [:show]
 
  def index
    @users = User.all.page(params[:page])
  end
 
  def show
    @user = User.find(params[:id])
    @room = Room.new
    @entry = Entry.new
    # @board = @user.boards.order('created_at desc')
    @boards = Board.where(user_id: @user.id)
  end
  
  
  def confirm 
     @user = User.find(confirm_params)
  end
  
  def likes
    @user = User.find(params[:id])
    @favboards = @user.favboards.page(params[:page])
    counts(@user)
  end
  
  
  def zipedit
    params.require(:user).permit(:postcode, :prefecture_code, :prefecture_name, :address_city, :address_street, :address_building)
  end
  
  private
  def confirm_params
      params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :gender, :postcode, :prefecture_code, :prefecture_name, :address_city, :address_street, :address_building, :college, :major, :email, :password, :password_confirmation)
  end
  
  def icon_params
      params.require(:user).permit(:icon)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_favorites.html.erb
<h2>お気に入り</h2>

<% if @user.favboards.present? %>
    <% @user.favboards.each do |board| %>
    　    <img src="/assets/heart_icon.svg" width="40" height="40">
    　    <a href="/boards/<%= board.id %>"><%= board.title %></a>
     <hr>
    <% end %>
<% else %>
 <p>まだ<%= current_user.last_name %>さんのお気に入りはありません。</p>
<% end %>

app/views/users/_history.html.erb
<h2>投稿履歴</h2>

<% if @user.boards.present? %>
    <% @user.boards.each do |board| %>
      <img src="/assets/post_icon.svg"  width="40" height="40">
      <a href="/boards/<%= board.id %>"><%= board.title %></a>
      <hr>
    <% end %>
<% else %>
   <p>まだ<%= current_user.last_name %>さんの投稿はありません。</p>
<% end %>

app/views/users/_icon.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :icon 'プロフィール画像' %><br>
    <%= f.file_field :icon, id: "myImage", accept: "image/*" %>
    <%= f.hidden_field :icon, :value => @user.icon %>
  </div>
  
  
  <!-- 追加個所 -->
  <div class="field">
    <% if @user.icon? %>
      <%= f.hidden_field :icon, :value => @user.icon %>
      <%= image_tag @user.icon.url, class: "user-icon" %>
    </div>
  <% end %><br>
    <%= image_tag '/assets/icon.png', class: "user-icon", id: "preview" %>
  </div>
  <div class="field">
    <!-- 既存レコード(DBに保存されている)かつ、画像が存在する場合 -->
    <% if @user.persisted? && @user.icon? %>
      <label>
      <%= f.check_box :remove_image %>
      画像を削除
    </label>
  <% end %>
  </div>
  <!-- 追加個所終了 -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script>
$('#myImage').on('change', function (e) {
    var reader = new FileReader();
    reader.onload = function (e) {
        $("#preview").attr('src', e.target.result);
    }
    reader.readAsDataURL(e.target.files[0]);
});
</script>

app/views/users/_profile.html.erb
<div class="card">
  <div class="card-body">
    <%= link_to '会員情報の編集', edit_user_registration_path, class: "link" %>
 <table class="profile">
   <tr>
      <th>お名前 </th>
      <td><%= @user.last_name %> <%= @user.first_name %></td>
   </tr>
   <tr>
      <th>お名前(ひらがな)</th>
    　<td><%= @user.last_name_kana %> <%= @user.first_name_kana %></td>
  </tr>
  <tr>
      <th>性別</th>
      <td><%= @user.gender %></td>
  </tr>
  <% if @user == current_user %>
  <tr>
      <th>メールアドレス</th>
      <td><%= @user.email %></td>
  </tr>
  <tr>
      <th>住所</th>
      <td>
        <label>郵便番号：</label><%= @user.postcode %></br><hr>
        <label>都道府県：</label><%= @user.prefecture_name %></br>
        <label>市町村区：</label><%= @user.address_city %></br>
        <label>番地名：</label><%= @user.address_street %><br>
        <% if @user.address_building.present? %>
        <label>ビル名：</label><%= @user.address_building %></br>
        <% end %>
      </td>
　</tr>
　<tr>
      <th>大学情報</th>
      <td>
        大学名：<%= @user.college %>
        学部名：<%= @user.major %>
      </td>
　</tr>
　<% end %>
 </table>
  <%= link_to '会員情報の削除', delete_path, class: "link", style: "color:red" %>
 </div>
</div> 
  

app/views/users/_rental.html.erb
<h2>レンタル履歴</h2>

<p>まだ<%= current_user.last_name %>さんがレンタルした本はありません。</p>

app/views/users/confirm.html.erb
<div class="mx-auto"style="width: 700px;">
 <div class="progress">
    <div class="progress-bar bg-info" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">75 ％</div>
     </div>

<h2>内容確認画面</h2>
    <div class="card bg-light ">
      <div class="col-14">
         <div class="card-header">
          </div>
      </div>
      <!--< form_tag(user_path, method: :get) do %>-->
      <table>
        <tr>
          <th>お名前</th>
          <td><%= @user.last_name %>　<%= @user.first_name %></td>
        </tr>
        <tr>
          <th>お名前(フリガナ)</th>
          <td><%= @user.last_name_kana %>　<%= @user.first_name_kana %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th>性別</th>
          <td><%= @user.gender %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td>
            <%= @user.postcode %>
            <%= @user.prefecture_name %>
            <%= @user.address_city %>
            <%= @user.address_street %>
            <%= @user.address_building %>
          </td>
        </tr>
        <tr>
          <th>大学情報</th>
          <td>
            <%= @user.college %>
            <%= @user.major %>
          </td>
        </tr>
      </table>
      
     <input class="btn btn-primary" type="submit" value="Submit">
 <!--<end %>-->

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<hr>
<div class="container">
<% @users.each do |u| %>
  <% if u.icon? %>
    <%= image_tag u.icon.url, class: "user-middle-icon" %>
<% else %>
    <%= image_tag "/assets/icon.png", class: "user-middle-icon" %>
<% end %>
  <p><a href="/users/<%= u.id %>"><%= u.last_name %><%= u.first_name %>さん</a></p>
  <hr>
<% end %>
<a href="/" class="btn btn-info">トップに戻る</a>
</div>

app/views/users/show.html.erb
<% if user_signed_in? %> 
  <% if @user == current_user %>
  <h2>
    　<!--current_user.last_name %>さん、こんにちは！-->
  </h2> 
   <% end %>
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-lg-4">
          <div class="card bg-light">
           <div class="card-header">アカウント情報</div>
            <div class="card-body">
              <div class="row">
                <div class="col-sm-6 col-xs-6">
                  <div class="icon-box">
                  　　<% if @user.icon? %>
                    　  　  <%= link_to edit_user_registration_path do %>
                            <%= image_tag @user.icon.url, class: "user-icon" %>
                          <% end %>
                      <% else %>
                          <%= link_to edit_user_registration_path do %>
                            <%= image_tag "/assets/icon.png", class: "user-icon", id: "preview"%>
                          <% end %>
                     <% end %>
                     </div>
                  </div>
                <div class="col-sm-6 col-xs-6">
                  <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    <a class="nav-link btn-light my-menu" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">プロフィール<i class="fas fa-chevron-right"></i></a>
                    <a class="nav-link btn-light my-menu" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">お気に入り<i class="fas fa-chevron-right"></i></a>
                    <a class="nav-link btn-light my-menu" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">投稿履歴<i class="fas fa-chevron-right"></i></a>
                    <a class="nav-link btn-light my-menu" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">レンタル履歴<i class="fas fa-chevron-right"></i></a>
                  </div>
                </div>
              </div>
            </div>
            
          </div>
        </div>
        <div class="col-xs-12 col-lg-8">
         <div class="tab-content" id="v-pills-tabContent">
          <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
            <%= render "users/profile"  %>
          </div>
          <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
            <%= render "users/favorites"  %>
          </div>
          <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
            <%= render "users/history"  %>
          </div>
          <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
            <%= render "users/rental"  %>
          </div>
         </div>
        </div>
        
        
        <%= form_for @room do |f| %>
        <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, :value => @user.id %>
        
        <% if @user == current_user %>
        <a href="/rooms" class="btn btn-info">チャット一覧を見る</a>
        <% else %>
        <%= f.submit "チャットを始める", :class => "btn btn-warning" %>
        <% end %>
       
        <% end %>
        <% end %>
      </div>
    </div>
  
  
<% else %>
 
  <h2> 現在ログインしていません </h2>
  <%= link_to "新規登録", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に移行する -->
  <%= link_to "ログイン", new_user_session_path, class: 
  'post' %> <!-- ログイン画面に移行する -->
<% end %>