config/routes.rb
Rails.application.routes.draw do
  

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'users/confirm' => "users#confirm"
  get "/books/:id" => "books#show"



  root 'welcome#index'

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
  }
  
  resources :boards , :only => [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :board_messages, :only => [:create, :edit, :destroy, :update]
  
  resources :admins, :only => [:index]
  
  devise_scope :user do
    post "update", :to => "users/registrations#update"
    get "delete", :to => "users/registrations#delete"
    patch "complete", :to => "users/registrations#complete"
  end
  
  resources :users, only: [:show, :index] do
    member do
     get :likes
    end
  end
  
  
  resources :books, only: [:index, :show]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :inquiries, only: [:index, :create, :new] do
    resources :answers, only: [:new, :create]
  end
  
  post 'inquiry/confirm' => 'inquiries#confirm'   

  


   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :inquiry
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploaders :images, ImgUploader
  serialize :images, JSON
  
  belongs_to :user
  has_many :board_messages
  has_many :favorites, dependent: :destroy
  has_many :liked_users, through: :favorites, source: :user
  
 def self.search(search)
  return Board.all unless search
    Board.where(['author LIKE ?', "%#{search}%"])
    .or(Board.where(['isbn_num LIKE ?', "%#{search}%"]))
    .or(Board.where(['book_name LIKE ?', "%#{search}%"]))
 end

end

# https://qiita.com/motty93/items/455515ede653371a5887

app/models/board_message.rb
class BoardMessage < ApplicationRecord
    belongs_to :user
    belongs_to :board
    # validates_uniqueness_of :board_id, scope: :user_id
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :board
    # validates_uniqueness_of :board_id, scope: :user_id
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
    belongs_to :user
    has_many :answers
end

app/models/like.rb
class Like < ApplicationRecord
    validates :user_id, {presence: true}
    validates :post_id, {presence: true}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
         
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :board_messages, dependent: :destroy
  has_many :boards, dependent: :destroy
  
  has_many :favorites, dependent: :destroy
  has_many :favboards, through: :favorites, source: :board

        
  def prefecture_name
     JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end   
  
  def prefecture_name=(prefecture_name)
     self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end 

   
  
  mount_uploader :icon, ImgUploader
  
  def update_without_current_password(params, *options)
  params.delete(:current_password)
  
      if params[:password].blank? && params[:password_confirmation].blank?
        params.delete(:password)
        params.delete(:password_confirmation)
      end
  
      result = update_attributes(params, *options)
      clean_up_passwords
      result
  end
    

  #お気にり登録判定
  def already_liked?(board)
    self.favorites.exists?(board_id: board.id)
  end 
    

end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
before_action :authenticate_user!, :only => [:index]
    
  def new
    @inquiry = Inquiry.new
    @inquiry.user_id = current_user.id
    # render :action => 'index'
  end 
  
  def index
    @inquiries = Inquiry.all.order(created_at: :desc)
  end
  
  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      render :action => 'confirm'
    else
      render :action => 'new'
    end
  end
  
  def create
    @inquiry = Inquiry.new(inquiry_params)
     respond_to do |format|
       if @inquiry.save
          ContactMailer.send_when_create(@inquiry).deliver
          ContactMailer.send_when_create_admin(@inquiry).deliver
          format.html { redirect_to root_path, notice: '問い合わせメッセージを送りました。'}
          format.json { render "home/top", status: :created, location: @inquiry}
       else
          flash[:notice] = "メッセージが送れませんでした。"
          format.html { render :new}
          format.json { render json: @inquiry.errors, status: :unprocessable_entity }
       end
     end
  end
  
  
  
  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :content, :user_id).merge(:user_id => current_user.id)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/inquiries/confirm.html.erb
<div class="page-header">
  <h2>お問い合わせ</h2>
</div>
 
<div class="col-8">
<%= form_for @inquiry do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :name %>
        <%= @inquiry.name %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @inquiry.email %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :content %>
        <%= simple_format(@inquiry.content) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'btn btn-primary' %>
<% end %>
</div>

app/views/inquiries/index.html.erb
<div class="container inquiry-index">
<h2>お問合せ一覧</h2>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th scope="col" style="width: 20%;">名前</th>
      <th scope="col" style="width: 20%;">メールアドレス</th>
      <th scope="col" style="width: 30%;">お問合せ</th>
      <th scope="col" style="width: 30%;">回答</th>
    </tr>
  </thead>
  <tbody>
   <% @inquiries.each do |inquiry| %>
    <tr>
      <th scope="row" style="width: 20%;"><%= inquiry.name %></th>
      <td style="width: 20%;"><%= inquiry.email %></td>
      <td style="width: 30%;">
        <%= link_to simple_format(inquiry.content), new_inquiry_answer_path(inquiry.id) %>
        <!--<inquiry.created_at. %>-->
        <%= simple_time(inquiry[:created_at])%>
      </td>
      <td style="width: 30%;">
        <% if Answer.find_by(inquiry_id: inquiry.id) %>
          <% Answer.where(inquiry_id: inquiry.id).each do |answer| %>
            <%= simple_format(answer.answer) %><br>
            <%= simple_time(answer.created_at) %><br>
            =======================<br>
          <% end %>
        <% end %>
      </td>
    </tr>
   <% end %>
  </tbody>
</table>
</div>
<style>
  
</style>

app/views/inquiries/new.html.erb
<%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
  <div class="page-header">
    <h2>お問い合わせ</h2>
  </div>
  <div class="container">
  <%= f.hidden_field :user_id, :value => current_user.id %>
 <div class="row justify-content-center">
 <div class="col-8">
  <table class="table">
    <tr>
      <th>名前　<span class="badge badge-danger">必須</span></th>
      <td>
        <div class="col-8">
          <%= f.text_field :name, autocomplete: "name", class: "form-control", required: true, placeholder: "例) 山田太郎"%>
        </div>
      </td>
    </tr>
    <tr>
      <th>メールアドレス　<span class="badge badge-danger">必須</span></th>
      <td>
        <div class="col-8">
          <%= f.email_field :email, autocomplete: "email", class: "form-control", required: true, placeholder: "例) yamada@gmail.com" %>
        </div>
      </td>
    </tr>
    <tr>
      <th>内容　<span class="badge badge-danger">必須</span></th>
      <td><%= f.text_area :content, autocomplete: "content", class: "form-control inquiry-content", required: true, placeholder: "こちらに問い合わせたい詳細について記載してください。" %></td>
    </tr>
  </table>
  <div class="row justify-content-center">
  <%= f.submit '送信する', class: 'btn btn-info btn-lg' %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/inquiries/thanks.html.erb
<div class="page-header">
  <h2>お問い合わせ</h2>
</div>
<div class="col-8">
<p>
  お問い合わせいただきありがとうございました。<br>
  問い合わせのご返信には２～３日かかりますのでご了承ください。
</p>
</div>