config/routes.rb
Rails.application.routes.draw do
  

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'users/confirm' => "users#confirm"
  get "/books/:id" => "books#show"



  root 'welcome#index'

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
  }
  
  resources :boards , :only => [:show, :index, :new, :create, :edit, :update, :destroy] do
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :board_messages, :only => [:create, :edit, :destroy, :update]
  
  resources :admins, :only => [:index]
  
  devise_scope :user do
    post "update", :to => "users/registrations#update"
    get "delete", :to => "users/registrations#delete"
    patch "complete", :to => "users/registrations#complete"
  end
  
  resources :users, only: [:show, :index] do
    member do
     get :likes
    end
  end
  
  
  resources :books, only: [:index, :show]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
  resources :inquiries, only: [:index, :create, :new] do
    resources :answers, only: [:new, :create]
  end
  
  post 'inquiry/confirm' => 'inquiries#confirm'   

  


   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :inquiry
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploaders :images, ImgUploader
  serialize :images, JSON
  
  belongs_to :user
  has_many :board_messages
  has_many :favorites, dependent: :destroy
  has_many :liked_users, through: :favorites, source: :user
  
 def self.search(search)
  return Board.all unless search
    Board.where(['author LIKE ?', "%#{search}%"])
    .or(Board.where(['isbn_num LIKE ?', "%#{search}%"]))
    .or(Board.where(['book_name LIKE ?', "%#{search}%"]))
 end

end

# https://qiita.com/motty93/items/455515ede653371a5887

app/models/board_message.rb
class BoardMessage < ApplicationRecord
    belongs_to :user
    belongs_to :board
    # validates_uniqueness_of :board_id, scope: :user_id
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :board
    # validates_uniqueness_of :board_id, scope: :user_id
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
    belongs_to :user
    has_many :answers
end

app/models/like.rb
class Like < ApplicationRecord
    validates :user_id, {presence: true}
    validates :post_id, {presence: true}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
    has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
         
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :board_messages, dependent: :destroy
  has_many :boards, dependent: :destroy
  
  has_many :favorites, dependent: :destroy
  has_many :favboards, through: :favorites, source: :board

        
  def prefecture_name
     JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end   
  
  def prefecture_name=(prefecture_name)
     self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end 

   
  
  mount_uploader :icon, ImgUploader
  
  def update_without_current_password(params, *options)
  params.delete(:current_password)
  
      if params[:password].blank? && params[:password_confirmation].blank?
        params.delete(:password)
        params.delete(:password_confirmation)
      end
  
      result = update_attributes(params, *options)
      clean_up_passwords
      result
  end
    

  #お気にり登録判定
  def already_liked?(board)
    self.favorites.exists?(board_id: board.id)
  end 
    

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/index.html.erb
<h1>ユーザー一覧</h1>
<hr>
<div class="container">
<% @users.each do |u| %>
  <% if u.icon? %>
    <%= image_tag u.icon.url, class: "user-middle-icon" %>
<% else %>
    <%= image_tag "/assets/icon.png", class: "user-middle-icon" %>
<% end %>
  <p><a href="/users/<%= u.id %>"><%= u.last_name %><%= u.first_name %>さん</a></p>
  <hr>
<% end %>
<a href="/" class="btn btn-info">トップに戻る</a>
</div>

app/views/layouts/_header.html.erb
  <div class="container">
    <div class="row justify-content-between">
      
        <a class="navbar-brand" href="/">
         <img src="/assets/logo.svg" class="logo" alt="テキストRentalアイコン">
        <strong class="texstore">テキストア
        </strong>
        </a>
         
     
       <div class="notices">
            <% if notice %>
              <p class = "alert alert-success"><%= notice %></p>
            <% end %>
            <% if alert %>
              <p class = "alert alert-danger"><%= alert %></p>
            <% end %> 
        </div>

   

       <div class="row justify-content-right">
         <div class="row"> 
          <% if user_signed_in? %>
                <% if current_user.id == 1 %>
                      <%= link_to admins_path, class: "my-link", style: "color:#FF9900" do %>
                      <span>管理者ページ</span>
                      <% end %>
                <% end %>
            <i class="nav-link nav-icon far fa-user icon"></i>
            <%= link_to user_path(current_user), class: "my-link" do %>
                <span class="my-link">マイページ</span>
            <% end %> 
          <% end %>
         </div>
         <!--<div class="row">-->
         <!-- <i class="nav-link nav-icon fas fa-shopping-cart icon" title="カートを見る"> </i>-->
         <!--  < link_to "#", class: "my-link" do %>-->
         <!--     <span class="my-link">カートをみる</span>-->
         <!--  < end %>-->
         <!--  </div>-->
          
         
         
         
         
        
         
        </div>
      </div>
     </div>
 

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNav">
      
      
      <div class=container>
       <ul class="nav justify-content-left">
           <!--<div class="col-9">-->
         
        <li class="nav-item my-2">
            <%= link_to '教科書を探す', boards_path, class: "nav-link"%>
        </li>
        
        <li class="nav-item my-2">
            <%= link_to '教科書を出品する', "/boards/new" , class: "nav-link"%>
        </li>
        
        <!--<li class="nav-item my-2">-->
        <!--    <%= link_to '教科書をさがす', books_path , class: "nav-link"%>-->
        <!--</li>-->
        
        <li class="nav-item my-2">
           <%= link_to 'お問い合わせ', new_inquiry_path, class: "nav-link" %>
        </li>
        <% unless user_signed_in? %>
        <li class="nav-item my-2">
            <%= link_to '無料会員登録', new_user_registration_path, class: "nav-link"%>
        </li> 
        <li class="nav-item my-2">
            <%= link_to 'ログイン', new_user_session_path, class: "nav-link" %>
        </li>
        <% else %>
        <li class="nav-item my-2">
          <%= link_to 'ログアウト', destroy_user_session_path, class: "nav-link", :method => "delete" %>
        </li>
        <% end %>
        
      </ul>
      </div>
        
        
        
        
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>テキストア</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--FontAwesomeのJS読み込み-->
    <script src="https://kit.fontawesome.com/cad4f40aba.js" crossorigin="anonymous"></script>
    <!--BootStrap4のスタイルシート-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <% favicon_link_tag('favicon.png') %>
    <link rel="icon" href="assets/favicon.png"> 
  </head>

  <body>
<!-- partial render -->
　　
        <%= render "layouts/header"  %>
        <%= render "layouts/navbar"  %>
    
    <%= yield %>
    <footer>
      <nav class="navbar navbar-light" style="background-color: rgb(0,136,157);">
          <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
    </ul>
      </nav>
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>    
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>-->
    <!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>-->
  </body>
</html>